<program> ::= <blanks> <item>*
<item> ::= <declaration> <blanks> | <clause> <blanks>
<clause> ::= <symbol> <gap> ">>" <gap> <symbol> <line> "|" <head> "|" <body> <blanks> "."
<head> ::= <gap> | <gap> <expr> <head_rest> <gap>
<head_rest> ::= "" | <gap> <expr> <head_rest> | <gap> "." <gap> <expr>
<body> ::= "" | <line> <goal> <body_rest>
<body_rest> ::= "" | <blanks> "," <line> <goal> <body_rest>
<line> ::= <blanks>
<symbol_code> ::= /./
<declaration> ::= <class_marker> <symbol> <gap> <options> <blanks> "." | "@+" <symbol> <gap> <extension_options> <blanks> "."
<class_marker> ::= "@"
<options> ::= <expr>
<extension_options> ::= <expr>
<expr> ::= "\#{" <blanks> <map_entries> <blanks> "}" | "{" <blanks> "}" | "{" <blanks> <goal> <goal_rest> <blanks> "}" | "[" <blanks> "]" | "[" <blanks> <expr> <list_rest> <blanks> "]" | "\"" <characters> "\"" | <symbol> | "(" <blanks> <form> <blanks> ")"
<map_entries> ::= "" | <entry> <entry_rest>
<entry_rest> ::= "" | <blanks> "," <pad> <entry> <entry_rest>
<entry> ::= <expr> <pad> "=>" <pad> <expr>
<goal> ::= <symbol> <spaced_exprs>
<goal_rest> ::= "" | <blanks> "," <pad> <goal> <goal_rest>
<list_rest> ::= "" | <blanks> "," <pad> <expr> <list_rest> | <pad> "." <pad> <expr>
<symbol> ::= <integer> | <variable_start_code> <symbol_code>* | <symbol_code> <symbol_code>*
<integer> ::= <natural> | "-" <natural>
<natural> ::= "0" | <digit> <digits>
<digits> ::= "" | <digit> <digits>
<digit> ::= /./
<characters> ::= "" | <character> <characters>
<character> ::= "\\\"" | "\\\\" | "\\n" | "\\t" | "\\r" | "\\\#" | "\#" | /./
<blank> ::= " " | "\n" | "\t" | "\r"
<blanks> ::= <blank> <blanks> | ""
<gap> ::= <blank> <blanks>
<pad> ::= <gap> | ""
<form> ::= <symbol> <spaced_exprs>
<spaced_exprs> ::= "" | <gap> <expr> <spaced_exprs>
